secretstore:
  provider: azure
  usePodIdentity: true
  keyvaultName: yourkeyvaultname
  secrets: []
  tenantId: yourazuretenantId

app:
  name: app-service-name
  aadpodidbinding: podidentity
  replicaCount: 1
  volumeMountName: secrets-store-inline
  secretProviderClass: azure-kv-podid
  volumeMountPath: /mnt/secrets-store
  volumeDriver: secrets-store.csi.k8s.io
  healthCheckPeriodSeconds: 3
  healthCheckTimeoutSeconds: 1
  secretEnv: []
  container:
    image: ghcr.io/your-username/your-repo:your-tag
    port: 80
    healthCheckHttpGetPath: /
  service:
    type: ClusterIP
    port: 80
  env:
  - key: PORT
    value: "80"
  
ingress:
  name: app-ingress-name
  replicaCount: 1
  dnsName: yourdnsname.westeurope.cloudapp.azure.com
  paths:
  - path: /*
    backend:
      serviceName: app-service-name
      servicePort: 80

keda: # KEDA (Kubernetes Event-Driven Autoscaler)
  enabled: false # KEDA is disabled by default
  name: app-service-name-keda
  authRefName: auth-trigger-app-service-name
  scaleTargetRef: app-service-name # service you would like to scale up/down
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus # an example for a KEDA scalar trigger (others also allowed)
    metadata:
      topicName: sbtopic-app-service
      subscriptionName: sbsub-app-service
      namespace: servicebus-app-ns
      messageCount: 50 # queue size treshold KEDA needs to hit to scale up/down 