name: ci

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Test2
        run: echo ${{ github.repository_owner }}
        
      - name: Test
        run: echo ${{ secrets.GITHUB_TOKEN }}
      
      - name: Save Helm Chart
        run: >
          export HELM_EXPERIMENTAL_OCI=1;
          helm chart save ./helm-app ghcr.io/bart-jansen/secretstore-ingress-apps-helm:latest;
          helm chart push ghcr.io/bart-jansen/secretstore-ingress-apps-helm:latest
          
      
        
#       - name: Push Helm Chart to GHCR
#         run: >
#           export HELM_EXPERIMENTAL_OCI=1;
          
        
