name: ci

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
        
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Save Helm Chart 
        run: >
          export HELM_EXPERIMENTAL_OCI=1;
          helm chart save helm-app ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}:latest
        
      - name: Push Helm Chart to GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}   
        run: >
          export HELM_EXPERIMENTAL_OCI=1;
          helm chart push ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}:latest
          
        
